### ISSUE TITLE
Subnegotiation parsing doesn't end correctly

### ISSUE THREAD

**Issue by LiquidityC** [envis10n/libtelnet-rs#8]
When extracting a subnegotiation event from the stream (eg. GMCP) the extration doesn't exit the
subnegotiation state properly resulting in subsequent parsing to error.

**Comment by LiquidityC** [comment]
Would it be possible to publish a new release to include this patch on crates.io?

**Comment by envis10n** [comment]
Sure thing, give me a bit to get to my desk and I'll get it published
-------- Original Message --------

**Comment by envis10n** [comment]
@LiquidityC it's been pushed to crates. Should be available now.

**Comment by LiquidityC** [comment]
Sweet. Thanks
